### ISSUE TITLE
Config permissions issues

### ISSUE THREAD

**Issue by brittonhayes** [GGP1/kure#3]
# Description

Hey there! Really like the idea of kure and would love to use it. Unfortunately, when attempting to run `kure`, it appears that there are some issues with the permissions being set by the config file or even with the permissions schema deeming a config eligible for reading by `kure`. 

This prevents me from using any subcommands because the config is read before every function call. I cannot even run the help command, so I would consider this fairly high severity.

It looks as though this was also spotted in your Github action `build` step here:
https://github.com/GGP1/kure/runs/1980446702#step:4:87

# Expected Behavior

```shell
# Desired behavior is the following command
# followed by no error and a successfully created yaml config
kure config create
```

# System Details

```yaml
# Systems where the error 
# has been replicated
systems:
 - name: "Pop OS"
   shell: "zsh"
   prompt: "starship"

 - name: "OSX"
   shell: "zsh"
   prompt: "starship"
```

# Possible Issues

I believe the issue is localized to the `/config` package in the repository as that is the only place dealing with file permissions for `~/.kure/kure.*` files. 

# Screenshots
![image](https://user-images.githubusercontent.com/46035482/109361712-5720b980-783e-11eb-9fea-bb877c9da74b.png)
![image](https://user-images.githubusercontent.com/46035482/109361739-66a00280-783e-11eb-89ca-c069215fae1e.png)

**Comment by GGP1** [comment]
The configuration folder that contains the configuration file is created using the permission 0600, here's where it happens:

```go
if err := os.MkdirAll(home, 0600); err != nil {
	return errors.Wrap(err, "couldn't create the configuration directory")
}
```
and so is the file created with the `kure config create` file:

```go
if err := os.WriteFile(opts.path, bytes.ToLower(cfgContent), 0600); err != nil {
	return errors.Wrap(err, "writing configuration skeleton")
}
```

Please make sure the configuration file is created by the same user that access it. If you keep receiving the same error it could be changed as the configuration file does not contain sensitive information.

**Comment by GGP1** [comment]
```go
viper.SetConfigPermissions(0600)
```

The configuration file has the file permissions **0600** (only the owner can read/write it). Please make sure the configuration file is created by the same user that access it. If you keep receiving the same error it could be changed  to **0666** so any user can read/write to it as the configuration file does not contain sensitive information.

**Comment by GGP1** [comment]
It looks like Kure is not recognizing the configuration file, which is strange as you've created it and in the configuration the file permission are set to **0600**:

```go
viper.SetConfigPermissions(0600)
```

The directory used to store the default configuration and the `config command` also have the same permissions. I guess it could be fixed by changing them to **0666**, do you have any way of checking that? Thanks for pointing this out.

**Comment by brittonhayes** [comment]
Hey @GGP1! Thanks for the quick reply. Really appreciate it. 

So I've gone ahead and tried creating the config file again from `kure` as the user that owns the file, and I still seem to be running into the same issue. 

Is there something I should be doing differently here?

# Steps Taken

1. set `KURE_CONFIG="~/.config/kure.yaml"` in `~/.zshenv`
2. `chown` the config file then 
2. list out permissions of config to see that I do indeed own the file as my user
3. attempt to run `kure` now


# Screenshots and my config

```yaml
# Identitation must be respected and paths must be absolute. 
# In case any of these values is omitted, Kure will use the default one.
# See ../configuration.md for further information.
clipboard:
  timeout: "15s" # Set to "0s" or leave blank for no timeout
  
database:
  path: "/home/britton/.config/kure.db" # Must be absolute

editor: "micro"

session:
  prefix: "kure:~$"
  timeout: "10m"  # Set to "0s" or leave blank for no timeout
```

![image](https://user-images.githubusercontent.com/46035482/109367687-a4575800-784b-11eb-8a21-b76dddcd9888.png)

![image](https://user-images.githubusercontent.com/46035482/109367724-bc2edc00-784b-11eb-809f-38fc2e733457.png)
![image](https://user-images.githubusercontent.com/46035482/109367792-ebdde400-784b-11eb-94c5-f73a5c2957dc.png)
